#!/bin/bash

# check if ~/.save not exists to create it
if [ ! -d ~/.save ]; then
  mkdir ~/.save
fi

cargs="${@:1}"

fl=$1
if [ "$fl" = "sudo" ]
then
  f1=$2
fi

if [ ! -z "$cargs" ];  then
  printf "$cargs\n" >> ~/.save/$fl
  echo "command successfully saved."
else
  echo "empty command cannot be saved :)"
  exit 1
fi
