#!/bin/bash

VERSION="0.0.1"
PARAMS=""

# Parse flags
# Only parse flags with one parameter
# Ignore all flags after first non flag or flag value
while (( "$#" )); do
  case "$1" in
    -a|--alias) # specify alias name for command
      # TODO: check if alias name is a command
      # check if command exists or not
      command -v $2
      if [ $? = 0 ]
      then
        printf "cannot use %s as alias. It is already a command in your system.\n" $2
        exit 1
      fi

      # throw error (with exit 1) if alias in path
      ALS=$2
      shift 2
      ;;
    -l|--list) # list of commands
      ls ~/.save/commands/
      shift 1
      exit 0
      ;;
    -c|--comment) # create a comment for command
      # TODO : check if comment is in '' or ""
      # it's because flag parser just parse one parameter
      CMNT=$2
      shift 2
      ;;

    -v|--version) # show save version and exit
      echo $VERSION
      exit 0
      ;;

    -h|--help) # help
      echo 'Save command help.' # TODO : write some help
      exit 0
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      break
      ;;
  esac
done

# check if ~/.save not exists to create it
[ -d ~/.save/commands ] || mkdir -p ~/.save/commands

# command to save
cargs="${@:1}"

# shift if sudo
if [ "$1" = "sudo" ]
then
  shift
fi

if [ ! -z "$cargs" ];  then
  # remove if command exactly exists in file
  [ -f ~/.save/commands/$1 ] && sed -i "/^$cargs\b/Id" ~/.save/commands/$1
  # echo command in file
  printf "$cargs\n" >> ~/.save/commands/$1
  # TODO : add alias and comment
  echo "command successfully saved."
else
  echo "empty command cannot be saved :)"
  exit 1
fi
